name: "Get Jar, Build And Publish"
description: "Get lavalink's jar, build the docker image of it and publish it to github"

inputs:
  tag:
    description: "tag of the release to use"
    required: true
  release:
    description: "is this a release (true/false)"
    required: true
  prerelease:
    description: "is this a prerelease (true/false)" 
    required: true
runs:
  using: "composite"
  steps:
    - 
      name: Download Jar
      uses: Legion2/download-release-action@v2.1.0
      with:
        repository: Lifeismana/RedLavalinkDocker  #Cog-Creators/Lavalink-Jars
        tag: ${{inputs.tag}}
        path: ${{env.GITHUB_WORKSPACE}}
        file: Lavalink.jar
