name: build_red_lavalink

on:
  release:
    # run on release and pre-release
    types: 
      - published

jobs:
  docker-build:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    permissions:
      packages: write
    env:
      TITLE: Red-Lavalink
      # * ↓ This needs to be changed when changing repo
      GHCR_SLUG: ghcr.io/lifeismana/redlavalinkdocker
    steps:
      - 
        name: Is last release a pre-release
        id: pre_release_in_front_of_release
        #is there a pre-release in front of the release
        uses: actions/github-script@v4
        with:
          # "Cog-Creators", "Lavalink-Jars"
          # *  This needs to be changed when changing repo ↓
          script: |
            const repoinfo = { owner:"Lifeismana", repo:"RedLavalinkDocker",}
            const {data: release} =  await github.repos.listReleases(repoinfo); 
            const sortedRelease = release.sort((Release_a,Release_b)=>Release_a.tag_name < Release_b.tag_name);
            return sortedRelease[0].prerelease;
      - 
        name: Checkout
        uses: actions/checkout@v2
        with:
          path: docker-build
      -
        name: Repo metadata
        id: repo
        uses: actions/github-script@v4
        with:
          script: |
            const repo = await github.repos.get(context.repo);
            return repo.data;
      - 
        name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - 
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - 
        name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        uses: ././docker-build/.github
        with:
          tag: ${{ github.event.release.tag_name }}
          prerelease: ${{ ! fromJson(steps.pre_release_in_front_of_release.outputs.result) || github.event.release.prerelease}}
          release: ${{ ! github.event.release.prerelease}}
          repodata: ${{ steps.repo.outputs.result }}